name: push_test
on: 
  push:
    branches:
      - main 
      - testing

jobs:
  start_up_jobs:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm install --save-dev jest
          npm run build --if-present
          npm run test --if-present
          npm test -- --coverage
     
            

